import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "./globals.css";
import Header from "@/component/header";


const inter = Prompt({ subsets: ['latin', 'thai'], weight: ['400', '700'] });

export const metadata: Metadata = {
  title: "phs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en">
          <body className={inter.className}>
              <Header />
              {children}
          </body>
        </html>
    );
}
